CREATE OR REPLACE TABLE `{DESTINATION_PROJECT_NAME}.{DESTINATION_DATASET_NAME}`.job_metrics_alerts_{INFOSCHEMA_PROJECT_NAME_FOR_TABLE}
 (  project_id STRING,
    message STRING,
    log_time TIMESTAMP
) PARTITION BY DATE(log_time);
